[package]
name = "ipstack"
version = "0.1.0"
authors = ["Michal Podhradsky <mpodhradsky@galois.com>"]

[dependencies]
#smoltcp = { version = "0.3", default-features = false, features = ["alloc,collections,log,verbose"] }