[package]
name = "rustserver"
version = "0.1.0"
authors = ["Michal Podhradsky <mpodhradsky@galois.com>"]

[lib]
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
# for the sel4-specific liblibc definitions
libc = { optional = true, git = "https://github.com/aisamanra/liblibc.git" }
